config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_scope :user do
    get    'signup', to: 'devise/registrations#new'
    post   'signup', to: 'devise/registrations#create'
    get    'login',  to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  devise_for :users

  resources :battles do
    resources :submissions, only: [:index, :create, :edit, :update, :destroy]
  end

  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
class Battle < ApplicationRecord
  include Imgurable
  include Likeable
  extend FriendlyId

  belongs_to :user
  has_many :submissions
  has_many :likes, class_name: :BattleLike

  validates_presence_of :title

  friendly_id :title, use: :slugged
end

app/models/battle_like.rb
class BattleLike < ApplicationRecord
  belongs_to :battle, counter_cache: :points
  belongs_to :user

  validates_presence_of :user_id, :battle_id
end

app/models/concerns/imgurable.rb
module Imgurable
  extend ActiveSupport::Concern

  included do
    validates_presence_of :link, :user_id
    validates :link, imgur: true, if: ->(b){b.link.present?}
    validates :title,       length: {maximum: 100}
    validates :description, length: {maximum: 1000}
  end
end

app/models/concerns/likeable.rb
module Likeable
  extend ActiveSupport::Concern

  included do
    scope :newest, ->{order created_at: :desc}
    scope :top,    ->{order points:     :desc}

    # liked by given user
    def liked_by user
      likes.create user_id: user.id
    end

    # check if liked by given user
    def liked_by? user
      likes.where(user_id: user.id).any?
    end

    # unliked by given user
    def unliked_by user
      liked = likes.find_by user_id: user.id
      liked&.destroy
    end
  end
end

app/models/submission.rb
class Submission < ApplicationRecord
  include Imgurable
  include Likeable

  belongs_to :user
  belongs_to :battle
  has_many :likes, class_name: :SubmissionLike

  validates_presence_of :battle_id
end

app/models/submission_like.rb
class SubmissionLike < ApplicationRecord
  belongs_to :submission, counter_cache: :points
  belongs_to :user

  validates_presence_of :user_id, :submission_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :battles
  has_many :submissions
  has_many :battle_likes
  has_many :submission_likes

  validates :username, presence: true, uniqueness: {case_sensitive: false},
                       length: {minimum: 3, maximum: 20},
                       format: {with:    /\A\w+\z/,
                                message: "only allows letters, numbers and underscores"}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :trackable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up,        keys: [:username]
    devise_parameter_sanitizer.permit :account_update, keys: [:username]
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_battle, except: [:index, :new, :create]
  before_action :owner, only: [:edit, :update, :destroy]

  def index
    @type = params[:type].downcase # "top" or "newest"
    @battles = Battle.send(@type)

    respond_to{|format| format.js}
  end

  def show
    @submission = Submission.new
  end

  def new
    @battle = current_user.battles.new
  end

  def create
    @battle = current_user.battles.build battle_params
    if @battle.valid?
      @battle.save
      flash[:success] = "Battle is successfully created!"
      redirect_to @battle
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @battle.update battle_params
      flash[:success] = "Battle is successfully updated!"
      redirect_back fallback_location: @battle
    else
      render "edit"
    end
  end

  def destroy
    if @battle.destroy
      flash[:success] = "Battle is successfully deleted!"
      redirect_to root_url
    else
      flash[:danger] = "There was an error when trying to delete the battle!"
      redirect_back fallback_location: root_url
    end
  end

  private

  def battle_params
    params.require(:battle).permit :title, :link, :description
  end

  def load_battle
    @battle = Battle.friendly.find params[:id]
  end

  # Filter: only owner can perform some certain actions
  def owner
    unless current_user == @battle.user
      flash[:danger] = "You're not authorized to perform this action!"
      redirect_back fallback_location: root_url
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @battles = Battle.top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_object
  before_action :not_owner

  def create
    @object.liked_by current_user

    respond_to{|format| format.js}
  end

  def destroy
    @object.unliked_by current_user

    respond_to{|format| format.js}
  end

  private

  def load_object
    if params[:type] == "battle"
      # load battle
      @object = Battle.find params[:object_id]
    else
      # load submission
      @object = Submission.find params[:object_id]
    end
  end

  # Filter: users can't like their own battles or submissions
  def not_owner
    redirect_back fallback_location: root_url if current_user.id == @object.user_id
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :load_battle
  before_action :load_submission, only: [:edit, :update, :destroy]
  before_action :owner,           only: [:edit, :update, :destroy]

  def index
    @type = params[:type].downcase # "top" or "newest"
    @submissions = @battle.submissions.send(@type)

    respond_to{|format| format.js}
  end

  def create
    @submission = current_user.submissions.build submission_params
    @submission.battle_id = @battle.id
    @submission.save

    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    @submission.update submission_params

    respond_to do |format|
      format.js do
        render :edit unless @submission.valid?
      end
    end
  end

  def destroy
    @submission.destroy
    flash[:success] = "Your submission is successfully deleted!"
    redirect_back fallback_location: @battle
  end

  private

  def submission_params
    params.require(:submission).permit :link, :title, :description
  end

  def load_battle
    @battle = Battle.friendly.find params[:battle_id]
  end

  def load_submission
    @submission = @battle.submissions.find params[:id]
  end

  # Filter: only owner can perform some certain actions
  def owner
    unless current_user == @submission.user
      flash[:danger] = "You're not authorized to perform this action!"
      redirect_back fallback_location: root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    page_title.empty? ? "Photoshop Battles" : page_title
  end

  def dom_id_for object
    "##{object.class.to_s.downcase}_#{object.id}"
  end
end

app/views/battles/_battle.html.erb
<div id="battle_<%= battle.id %>" class="battle">
  <div class="row">
    <div class="col-md-2 offset-md-2">
      <%= render "shared/likes", object: battle %>
    </div>
    <div class="col-md-6">
      <h2><%= link_to battle.title, battle %></h2>
    </div>
  </div>


  <div class="row">
    <div class="col-md-8 offset-md-2">
      <section class="battle-image">
        <%= image_tag battle.link, width: 500 %>
      </section>
      <% unless battle.description.nil? %>
        <p><%= battle.description %></p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 offset-md-2">
    <p>
      Post by <%= battle.user.username %>,
      <%= time_ago_in_words battle.created_at %> ago
      <% if current_user == battle.user %>
        |
        <%= link_to "edit", edit_battle_path(battle) %>
        |
        <%= link_to "delete", battle, method: :delete, data: {confirm: "You sure?"} %>
      <% end %>
    </p>
      </div>
  </div>
</div>

app/views/battles/_battle_form.html.erb
<%= form_for @battle do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
    <%= render "shared/error_message", object: @battle, field: :title %>
  </div>

  <div class="form-group">
    <%= f.label :link, "Imgur link" %>
    <%= f.text_field :link, class: "form-control" %>
    <small class="form-text text-muted">
      Example: https://imgur.com/YP8CxhH or https://i.imgur.com/YP8CxhH.jpg
    </small>
    <%= render "shared/error_message", object: @battle, field: :link %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
    <%= render "shared/error_message", object: @battle, field: :description %>
  </div>

  <div class="form-group">
    <%= f.submit button_text, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/battles/edit.html.erb
<% provide :title, "Edit battle" %>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h2 class="center">Create a new battle</h2>
    <%= render "battle_form", button_text: "Update" %>
  </div>
</div>

app/views/battles/index.js.erb
$("#battles").html(
  "<%= j render(@battles) %>"
);

$("#sort_by_links .active").removeClass("active");
$("#<%= @type %>_link").addClass("active");

app/views/battles/new.html.erb
<% provide :title, "Create a new battle" %>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h2 class="center">Create a new battle</h2>
    <%= form_for @battle do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control" %>
        <%= render "shared/error_message", object: @battle, field: :title %>
      </div>

      <div class="form-group">
        <%= f.label :link, "Imgur link" %>
        <%= f.text_field :link, class: "form-control" %>
        <small class="form-text text-muted">
          Example: https://imgur.com/YP8CxhH or https://i.imgur.com/YP8CxhH.jpg
        </small>
        <%= render "shared/error_message", object: @battle, field: :link %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
        <%= render "shared/error_message", object: @battle, field: :description %>
      </div>

      <div class="form-group">
        <%= f.submit "Create battle", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/battles/show.html.erb
<% provide :title, @battle.title %>

<%= render @battle %>

<% if user_signed_in? %>
  <div id="submission_form">
    <%= render "shared/submission_form", button: "Submit" %>
  </div>
<% end %>

<% if @battle.submissions.any? %>
  <div id="sort_by_links" class="row">
    <div class="offset-md-2 col-md-6">
    <%= link_to "Top", battle_submissions_path(@battle), id: "top_link",
                remote: true, data: {params: "type=top"}, class: "active" %>
    |
    <%= link_to "Newest", battle_submissions_path(@battle), id: "newest_link",
                remote: true, data: {params: "type=newest"} %>
    </div>
  </div>
  <div id="submissions">
      <%= render @battle.submissions.top %>
  </div>
<% end %>

app/views/home/index.html.erb
<% if @battles.any? %>
  <div id="sort_by_links" class="row">
    <div class="offset-md-2 col-md-6">
    <%= link_to "Top", battles_path, id: "top_link",
                remote: true, data: {params: "type=top"}, class: "active" %>
    |
    <%= link_to "Newest", battles_path, id: "newest_link",
                remote: true, data: {params: "type=newest"} %>
    </div>
  </div>

  <div id="battles">
    <%= render @battles %>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <% type = "success" if "notice" == type %>
    <% type = "danger"  if "alert"  == type %>

    <%= content_tag(:div, message, class: "alert alert-#{type}") %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="container">
  <a href="https://github.com/52/psbattles">Github Repo</a>
  <%= debug params if Rails.env.development? %>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title yield(:title) %></title>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<navbar class="navbar navbar-expand-lg navbar-fixed-top fixed-top navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Photoshop Battles", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Create New Battle", new_battle_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Profile</a>
              <%= link_to "Account", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</navbar>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/likes/_points.js.erb
$("<%= dom_id_for @object %> .points").html(
  "<%= pluralize @object.likes.count + 1, 'point' %>"
);

app/views/likes/create.js.erb
<%= render "points" %>

$("<%= dom_id_for @object %> .like_form").html(
  "<%= j render('shared/unlike_button', object: @object) %>"
);

app/views/likes/destroy.js.erb
<%= render "points" %>

$("<%= dom_id_for @object %> .like_form").html(
  "<%= j render('shared/like_button', object: @object) %>"
);

app/views/shared/_error_message.html.erb
<% if object.errors[field].any? %>
  <div class="invalid-feedback">
    <%= "#{field.to_s.humanize} #{object.errors[field][0]}" %>
  </div>
<% end %>

app/views/shared/_highlight_error_field.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $(".field_with_errors input").addClass("is-invalid");
  });
</script>

app/views/shared/_like_button.html.erb
<%= form_tag likes_path, remote: true do %>
  <%= hidden_field_tag :type, object.class.to_s.downcase %>
  <%= hidden_field_tag :object_id, object.id %>
  <%= submit_tag "Like", class: "btn btn-primary" %>
<% end %>

app/views/shared/_likes.html.erb
<span class="points">
  <%= pluralize object.points, "point" %>
</span>
<% if user_signed_in? && current_user != object.user %>
  <div class="like_form">
    <% if object.liked_by? current_user %>
      <%= render "shared/unlike_button", object: object %>
    <% else %>
      <%= render "shared/like_button", object: object %>
    <% end %>
  </div>
<% end %>

app/views/shared/_submission_form.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= form_for [@battle, @submission], remote: true do |f| %>
      <div class="form-group">
        <%= f.text_field :link, placeholder: "Imgur.com link", class: "form-control" %>
        <%= render "shared/error_message", object: @submission, field: :link %>
      </div>

      <div class="form-group">
        <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
        <%= render "shared/error_message", object: @submission, field: :title %>
      </div>

      <div class="form-group">
        <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
        <%= render "shared/error_message", object: @submission, field: :description %>
      </div>

      <div class="form-group">
        <%= f.submit button, class: "btn btn-primary" %>
      </div>

    <% end %>
  </div>
</div>

<%= render "shared/highlight_error_field" %>

app/views/shared/_unlike_button.html.erb
<% like = object.likes.find_by user_id: current_user.id %>
<%= form_tag like_path(like), method: :delete, remote: true do %>
  <%= hidden_field_tag :type, object.class.to_s.downcase %>
  <%= hidden_field_tag :object_id, object.id %>
  <%= submit_tag "Unlike", class: "btn" %>
<% end %>

app/views/submissions/_submission.html.erb
<div class="submission" id="submission_<%= submission.id %>">
  <div class="row">
    <div class="col-md-1 offset-md-2">
      <%= submission.user.username %>
    </div>
    <div class="col-md-6">
      <% unless submission.title.nil? %>
        <%= submission.title %>
      <% end %>
    </div>
    <div class="col-md-2">
      <%= render "shared/likes", object: submission %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 offset-md-3">
      <section>
        <%= image_tag submission.link, width: 400 %>
      </section>
      <% unless submission.description.nil? %>
        <p><%= submission.description %></p>
      <% end %>

      <div>
        <%= time_ago_in_words submission.created_at %> ago
        <% if user_signed_in? && current_user == submission.user %>
          |
          <%= link_to "edit",
                      edit_battle_submission_path(submission.battle, submission),
                      remote: true %>
          |
          <%= link_to "delete", [submission.battle, submission],
                                method: :delete, remote: true,
                                data: {confirm: "You sure?"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/submissions/create.js.erb
<% if @submission.valid? %>
  $("#submission_form").remove();
  $('#submissions').prepend("<%= j render(@submission) %>");
<% else %>
  $("#submission_form").html(
    "<%= j render('shared/submission_form', button: 'Submit') %>"
  );
  <% end %>

app/views/submissions/edit.js.erb
$("#submission_<%= @submission.id %>").html(
  "<%= j render('shared/submission_form' ,button: 'Update') %>"
);

app/views/submissions/index.js.erb
$("#submissions").html(
  "<%= j render(@submissions) %>"
);

$("#sort_by_links .active").removeClass("active");
$("#<%= @type %>_link").addClass("active");

app/views/submissions/update.js.erb
$("#submission_<%= @submission.id %>").html(
  "<%= j render(@submission) %>"
);